"""rename department

Revision ID: 2a1898e4f12a
Revises: fbf3cd2a4e63
Create Date: 2024-10-06 20:25:15.365145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1898e4f12a'
down_revision = 'fbf3cd2a4e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
